name: hikersafrique
description: An Application for Hiking
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <3.3.0'

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  google_nav_bar: ^5.0.6
  curved_navigation_bar: ^1.0.3
  provider: ^6.0.5
  email_validator: ^2.1.17
  flutter_spinkit: ^5.1.0
  firebase_core: ^2.7.0
  pdf: ^3.9.0
  printing: ^5.10.4
  uuid: ^3.0.7
  url_launcher: ^6.1.11
  flutter_dotenv: ^5.0.2
  flutterwave_standard: 1.0.2
  file_picker: ^5.3.2
  firebase_storage: ^11.2.8
  fluttertoast: ^8.2.2
  logger: ^1.1.0
  flutter_lints: ^2.0.0
  image_picker: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/.env

  fonts:
    - family: Cera-Pro
      fonts:
        - asset: fonts/Cera-Pro-Bold.otf
        - asset: fonts/Cera-Pro-Medium.otf
